name: Deploy to GitHub Pages

on:
  push:
    branches: "develop"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest

    env:
      BACKEND_URL: https://ecommerce-8yj0ak36.b4a.run/
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Cache dependencies
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: ./Frontend/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        shell: bash
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: cd Frontend && npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          echo "BASE_PATH='/${{ github.event.repository.name }}'" > Frontend/.env
          cd Frontend && npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./Frontend/out"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
